; IconPointers indexes (see data/icon_pointers.asm)
	const_def
	const ICON_NULL       ; 00
	const ICON_BULBASAUR  ; 01
	const ICON_IVYSAUR    ; 02
	const ICON_VENUSAUR   ; 03
	const ICON_CHARMANDER ; 04
	const ICON_CHARMELEON ; 05
	const ICON_CHARIZARD  ; 06
	const ICON_SQUIRTLE   ; 07
	const ICON_WARTORTLE  ; 08
	const ICON_BLASTOISE  ; 09
	const ICON_CATERPIE   ; 0a
	const ICON_METAPOD    ; 0b
	const ICON_BUTTERFREE ; 0c
	const ICON_WEEDLE     ; 0d
	const ICON_KAKUNA     ; 0e
	const ICON_BEEDRILL   ; 0f
	const ICON_PIDGEY     ; 10
	const ICON_PIDGEOTTO  ; 11
	const ICON_PIDGEOT    ; 12
	const ICON_RATTATA    ; 13
	const ICON_RATICATE   ; 14
	const ICON_SPEAROW    ; 15
	const ICON_FEAROW     ; 16
	const ICON_EKANS      ; 17
	const ICON_ARBOK      ; 18
	const ICON_PIKACHU    ; 19
	const ICON_RAICHU     ; 1a
	const ICON_SANDSHREW  ; 1b
	const ICON_SANDSLASH  ; 1c
	const ICON_NIDORAN_F  ; 1d
	const ICON_NIDORINA   ; 1e
	const ICON_NIDOQUEEN  ; 1f
	const ICON_NIDORAN_M  ; 20
	const ICON_NIDORINO   ; 21
	const ICON_NIDOKING   ; 22
	const ICON_CLEFAIRY   ; 23
	const ICON_CLEFABLE   ; 24
	const ICON_VULPIX     ; 25
	const ICON_NINETALES  ; 26
	const ICON_JIGGLYPUFF ; 27
	const ICON_WIGGLYTUFF ; 28
	const ICON_ZUBAT      ; 29
	const ICON_GOLBAT     ; 2a
	const ICON_ODDISH     ; 2b
	const ICON_GLOOM      ; 2c
	const ICON_VILEPLUME  ; 2d
	const ICON_PARAS      ; 2e
	const ICON_PARASECT   ; 2f
	const ICON_VENONAT    ; 30
	const ICON_VENOMOTH   ; 31
	const ICON_DIGLETT    ; 32
	const ICON_DUGTRIO    ; 33
	const ICON_MEOWTH     ; 34
	const ICON_PERSIAN    ; 35
	const ICON_PSYDUCK    ; 36
	const ICON_GOLDUCK    ; 37
	const ICON_MANKEY     ; 38
	const ICON_PRIMEAPE   ; 39
	const ICON_GROWLITHE  ; 3a
	const ICON_ARCANINE   ; 3b
	const ICON_POLIWAG    ; 3c
	const ICON_POLIWHIRL  ; 3d
	const ICON_POLIWRATH  ; 3e
	const ICON_ABRA       ; 3f
	const ICON_KADABRA    ; 40
	const ICON_ALAKAZAM   ; 41
	const ICON_MACHOP     ; 42
	const ICON_MACHOKE    ; 43
	const ICON_MACHAMP    ; 44
	const ICON_BELLSPROUT ; 45
	const ICON_WEEPINBELL ; 46
	const ICON_VICTREEBEL ; 47
	const ICON_TENTACOOL  ; 48
	const ICON_TENTACRUEL ; 49
	const ICON_GEODUDE    ; 4a
	const ICON_GRAVELER   ; 4b
	const ICON_GOLEM      ; 4c
	const ICON_PONYTA     ; 4d
	const ICON_RAPIDASH   ; 4e
	const ICON_SLOWPOKE   ; 4f
	const ICON_SLOWBRO    ; 50
	const ICON_MAGNEMITE  ; 51
	const ICON_MAGNETON   ; 52
	const ICON_FARFETCH_D ; 53
	const ICON_DODUO      ; 54
	const ICON_DODRIO     ; 55
	const ICON_SEEL       ; 56
	const ICON_DEWGONG    ; 57
	const ICON_GRIMER     ; 58
	const ICON_MUK        ; 59
	const ICON_SHELLDER   ; 5a
	const ICON_CLOYSTER   ; 5b
	const ICON_GASTLY     ; 5c
	const ICON_HAUNTER    ; 5d
	const ICON_GENGAR     ; 5e
	const ICON_ONIX       ; 5f
	const ICON_DROWZEE    ; 60
	const ICON_HYPNO      ; 61
	const ICON_KRABBY     ; 62
	const ICON_KINGLER    ; 63
	const ICON_VOLTORB    ; 64
	const ICON_ELECTRODE  ; 65
	const ICON_EXEGGCUTE  ; 66
	const ICON_EXEGGUTOR  ; 67
	const ICON_CUBONE     ; 68
	const ICON_MAROWAK    ; 69
	const ICON_HITMONLEE  ; 6a
	const ICON_HITMONCHAN ; 6b
	const ICON_LICKITUNG  ; 6c
	const ICON_KOFFING    ; 6d
	const ICON_WEEZING    ; 6e
	const ICON_RHYHORN    ; 6f
	const ICON_RHYDON     ; 70
	const ICON_CHANSEY    ; 71
	const ICON_TANGELA    ; 72
	const ICON_KANGASKHAN ; 73
	const ICON_HORSEA     ; 74
	const ICON_SEADRA     ; 75
	const ICON_GOLDEEN    ; 76
	const ICON_SEAKING    ; 77
	const ICON_STARYU     ; 78
	const ICON_STARMIE    ; 79
	const ICON_MR__MIME   ; 7a
	const ICON_SCYTHER    ; 7b
	const ICON_JYNX       ; 7c
	const ICON_ELECTABUZZ ; 7d
	const ICON_MAGMAR     ; 7e
	const ICON_PINSIR     ; 7f
	const ICON_TAUROS     ; 80
	const ICON_MAGIKARP   ; 81
	const ICON_GYARADOS   ; 82
	const ICON_LAPRAS     ; 83
	const ICON_DITTO      ; 84
	const ICON_EEVEE      ; 85
	const ICON_VAPOREON   ; 86
	const ICON_JOLTEON    ; 87
	const ICON_FLAREON    ; 88
	const ICON_PORYGON    ; 89
	const ICON_OMANYTE    ; 8a
	const ICON_OMASTAR    ; 8b
	const ICON_KABUTO     ; 8c
	const ICON_KABUTOPS   ; 8d
	const ICON_AERODACTYL ; 8e
	const ICON_SNORLAX    ; 8f
	const ICON_ARTICUNO   ; 90
	const ICON_ZAPDOS     ; 91
	const ICON_MOLTRES    ; 92
	const ICON_DRATINI    ; 93
	const ICON_DRAGONAIR  ; 94
	const ICON_DRAGONITE  ; 95
	const ICON_MEWTWO     ; 96
	const ICON_MEW        ; 97
	const ICON_CHIKORITA  ; 98
	const ICON_BAYLEEF    ; 99
	const ICON_MEGANIUM   ; 9a
	const ICON_CYNDAQUIL  ; 9b
	const ICON_QUILAVA    ; 9c
	const ICON_TYPHLOSION ; 9d
	const ICON_TOTODILE   ; 9e
	const ICON_CROCONAW   ; 9f
	const ICON_FERALIGATR ; a0
	const ICON_SENTRET    ; a1
	const ICON_FURRET     ; a2
	const ICON_HOOTHOOT   ; a3
	const ICON_NOCTOWL    ; a4
	const ICON_LEDYBA     ; a5
	const ICON_LEDIAN     ; a6
	const ICON_SPINARAK   ; a7
	const ICON_ARIADOS    ; a8
	const ICON_CROBAT     ; a9
	const ICON_CHINCHOU   ; aa
	const ICON_LANTURN    ; ab
	const ICON_PICHU      ; ac
	const ICON_CLEFFA     ; ad
	const ICON_IGGLYBUFF  ; ae
	const ICON_TOGEPI     ; af
	const ICON_TOGETIC    ; b0
	const ICON_NATU       ; b1
	const ICON_XATU       ; b2
	const ICON_MAREEP     ; b3
	const ICON_FLAAFFY    ; b4
	const ICON_AMPHAROS   ; b5
	const ICON_BELLOSSOM  ; b6
	const ICON_MARILL     ; b7
	const ICON_AZUMARILL  ; b8
	const ICON_SUDOWOODO  ; b9
	const ICON_POLITOED   ; ba
	const ICON_HOPPIP     ; bb
	const ICON_SKIPLOOM   ; bc
	const ICON_JUMPLUFF   ; bd
	const ICON_AIPOM      ; be
	const ICON_SUNKERN    ; bf
	const ICON_SUNFLORA   ; c0
	const ICON_YANMA      ; c1
	const ICON_WOOPER     ; c2
	const ICON_QUAGSIRE   ; c3
	const ICON_ESPEON     ; c4
	const ICON_UMBREON    ; c5
	const ICON_MURKROW    ; c6
	const ICON_SLOWKING   ; c7
	const ICON_MISDREAVUS ; c8
	const ICON_UNOWN      ; c9
	const ICON_WOBBUFFET  ; ca
	const ICON_GIRAFARIG  ; cb
	const ICON_PINECO     ; cc
	const ICON_FORRETRESS ; cd
	const ICON_DUNSPARCE  ; ce
	const ICON_GLIGAR     ; cf
	const ICON_STEELIX    ; d0
	const ICON_SNUBBULL   ; d1
	const ICON_GRANBULL   ; d2
	const ICON_QWILFISH   ; d3
	const ICON_SCIZOR     ; d4
	const ICON_SHUCKLE    ; d5
	const ICON_HERACROSS  ; d6
	const ICON_SNEASEL    ; d7
	const ICON_TEDDIURSA  ; d8
	const ICON_URSARING   ; d9
	const ICON_SLUGMA     ; da
	const ICON_MAGCARGO   ; db
	const ICON_SWINUB     ; dc
	const ICON_PILOSWINE  ; dd
	const ICON_CORSOLA    ; de
	const ICON_REMORAID   ; df
	const ICON_OCTILLERY  ; e0
	const ICON_DELIBIRD   ; e1
	const ICON_MANTINE    ; e2
	const ICON_SKARMORY   ; e3
	const ICON_HOUNDOUR   ; e4
	const ICON_HOUNDOOM   ; e5
	const ICON_KINGDRA    ; e6
	const ICON_PHANPY     ; e7
	const ICON_DONPHAN    ; e8
	const ICON_PORYGON2   ; e9
	const ICON_STANTLER   ; ea
	const ICON_SMEARGLE   ; eb
	const ICON_TYROGUE    ; ec
	const ICON_HITMONTOP  ; ed
	const ICON_SMOOCHUM   ; ee
	const ICON_ELEKID     ; ef
	const ICON_MAGBY      ; f0
	const ICON_MILTANK    ; f1
	const ICON_BLISSEY    ; f2
	const ICON_RAIKOU     ; f3
	const ICON_ENTEI      ; f4
	const ICON_SUICUNE    ; f5
	const ICON_LARVITAR   ; f6
	const ICON_PUPITAR    ; f7
	const ICON_TYRANITAR  ; f8
	const ICON_LUGIA      ; f9
	const ICON_HO_OH      ; fa
	const ICON_CELEBI     ; fb
	const ICON_EGG        ; fc
NUM_ICONS EQU const_value - 1

; LoadMenuMonIcon.Jumptable indexes (see engine/gfx/mon_icons.asm)
	const_def
	const MONICON_PARTYMENU
	const MONICON_NAMINGSCREEN
	const MONICON_MOVES
	const MONICON_TRADE
	const MONICON_MOBILE1
	const MONICON_MOBILE2
	const MONICON_UNUSED

; party menu icon palettes
	const_def
	const PAL_ICON_RED    ; 0
	const PAL_ICON_BLUE   ; 1
	const PAL_ICON_GREEN  ; 2
	const PAL_ICON_BROWN  ; 3
	const PAL_ICON_PINK   ; 4
	const PAL_ICON_DUMMY1 ; 5
	const PAL_ICON_DUMMY2 ; 6
	const PAL_ICON_DUMMY3 ; 7
