	tilepal 0, GRAY, BROWN, BROWN, GREEN, GREEN, GREEN, BROWN, ROOF
	tilepal 0, ROOF, RED, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, GREEN, WATER, GREEN, GRAY, RED
	tilepal 0, ROOF, ROOF, RED, RED, RED, BROWN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, BROWN, ROOF, ROOF, GRAY, ROOF, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, BROWN, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 1, GREEN, RED, RED, RED, GRAY, GRAY, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, RED, RED, RED, GREEN, ROOF
	tilepal 1, ROOF, RED, RED, RED, GRAY, GRAY, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, RED, RED, RED, GRAY, GRAY
	tilepal 1, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, RED, RED
	tilepal 1, ROOF, ROOF, GREEN, GREEN, ROOF, ROOF, GREEN, GREEN
	tilepal 1, ROOF, GREEN, GRAY, GRAY, RED, RED, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, YELLOW, GREEN, GREEN, YELLOW
	tilepal 1, ROOF, ROOF, BROWN, BROWN, WATER, WATER, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, ROOF, ROOF, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
