	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, WATER, GRAY, GRAY, RED, RED, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, ROOF, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, WATER, WATER, WATER, GRAY, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY, BROWN
	tilepal 0, RED, RED, BROWN, GRAY, GREEN, GREEN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN, RED
	tilepal 0, BROWN, BROWN, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, BROWN, WATER
	tilepal 0, WATER, WATER, GRAY, BROWN, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, BROWN, BROWN, RED, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, ROOF, ROOF, ROOF, BROWN, BROWN, GRAY
	tilepal 1, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY, BROWN, BROWN
	tilepal 1, GRAY, GRAY, ROOF, ROOF, ROOF, BROWN, BROWN, GRAY
	tilepal 1, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY
	tilepal 1, BROWN, BROWN, ROOF, ROOF, ROOF, GRAY, GRAY, GRAY
	tilepal 1, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY
	tilepal 1, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY
	tilepal 1, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, GRAY, GRAY
	tilepal 1, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
