	tilepal 0, RED, BROWN, GRAY, GREEN, BROWN, GREEN, BROWN, GRAY
	tilepal 0, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, RED, RED, RED, BROWN, WATER, BROWN, BROWN, GRAY
	tilepal 0, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, RED, RED, RED, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GREEN, BROWN, BROWN, BROWN, YELLOW, GREEN, GREEN, YELLOW
	tilepal 0, RED, RED, RED, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN

rept 16
	db $ff
endr

	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 1, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 1, GREEN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, BROWN, GREEN, BROWN, BROWN, GREEN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
