	tilepal 0, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GREEN, GREEN, BROWN, BROWN, WATER, WATER
	tilepal 0, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF
	tilepal 0, ROOF, ROOF, GREEN, GREEN, BROWN, BROWN, WATER, WATER
	tilepal 0, WATER, GRAY, GRAY, WATER, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, WATER, GREEN, GREEN, WATER, WATER, WATER, WATER
	tilepal 0, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, WATER, GREEN, GREEN, WATER, WATER, WATER, WATER
	tilepal 0, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, YELLOW, YELLOW, GRAY, GRAY, WATER, WATER, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, GRAY, GRAY, WATER, WATER

rept 16
	db $ff
endr

	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, GREEN, GREEN
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, WATER, WATER
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, GREEN, GREEN
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
