	tilepal 0, GRAY, BROWN, BROWN, GREEN, GREEN, GREEN, BROWN, ROOF
	tilepal 0, ROOF, RED, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, GREEN, WATER, GREEN, GRAY, RED
	tilepal 0, ROOF, ROOF, BROWN, BROWN, BROWN, GRAY, GREEN, GREEN
	tilepal 0, GRAY, GRAY, BROWN, ROOF, ROOF, GRAY, ROOF, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, BROWN, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, GRAY, BROWN, BROWN, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, RED, RED, RED, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, RED, ROOF, ROOF, GRAY, GRAY, ROOF, ROOF
	tilepal 1, RED, RED, RED, RED, RED, RED, GRAY, GRAY
	tilepal 1, GRAY, ROOF, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, RED, RED, RED, RED, RED, RED, GRAY, GRAY
	tilepal 1, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, YELLOW, GREEN, GREEN, YELLOW
	tilepal 1, ROOF, ROOF, BROWN, BROWN, WATER, WATER, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, ROOF, ROOF, BROWN, BROWN, WATER, WATER, GREEN, GREEN
	tilepal 1, ROOF, ROOF, GREEN, GREEN, RED, RED, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, RED, GREEN
