	tilepal 0, GRAY, BROWN, YELLOW, YELLOW, BROWN, BROWN, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, YELLOW, YELLOW
	tilepal 0, GRAY, GRAY, YELLOW, YELLOW, BROWN, BROWN, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW, YELLOW
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, GRAY, GRAY
	tilepal 0, BROWN, BROWN, WATER, WATER, WATER, WATER, YELLOW, YELLOW
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, YELLOW, YELLOW, WATER, WATER, YELLOW, YELLOW
	tilepal 0, WATER, WATER, WATER, WATER, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, WATER, WATER, WATER, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, GRAY, GRAY, GRAY, WATER, WATER, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, GRAY, GRAY, GRAY, WATER, WATER, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
