	tilepal 0, BROWN, GRAY, BROWN, BROWN, BROWN, YELLOW, YELLOW, GREEN
	tilepal 0, GREEN, RED, RED, GRAY, GRAY, RED, RED, RED
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, YELLOW, YELLOW, GREEN
	tilepal 0, GREEN, RED, RED, GRAY, GRAY, WATER, RED, RED
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, YELLOW, YELLOW, GREEN
	tilepal 0, GREEN, WATER, WATER, GRAY, GRAY, ROOF, RED, RED
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, YELLOW, YELLOW, GREEN
	tilepal 0, GREEN, WATER, WATER, WATER, WATER, GREEN, RED, RED
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN
	tilepal 0, GREEN, ROOF, ROOF, WATER, WATER, GRAY, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN
	tilepal 0, GREEN, ROOF, ROOF, YELLOW, YELLOW, GRAY, ROOF, ROOF

rept 16
	db $ff
endr

	tilepal 1, RED, RED, WATER, WATER, ROOF, ROOF, GRAY, GREEN
	tilepal 1, GREEN, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 1, GREEN, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 1, GREEN, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 1, GREEN, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN
	tilepal 1, GREEN, YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN
	tilepal 1, GREEN, YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
