	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, GRAY, BROWN
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, WATER, WATER, WATER, WATER
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN, WATER, WATER
	tilepal 0, RED, RED, GREEN, GREEN, BROWN, BROWN, GRAY, GREEN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN, WATER, WATER

rept 16
	db $ff
endr

	tilepal 1, WATER, WATER, WATER, WATER, GREEN, GREEN, WATER, WATER
	tilepal 1, WATER, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 1, WATER, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, ROOF, ROOF, GRAY, GRAY, GRAY, ROOF, GRAY, GRAY
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, GRAY, GRAY, GRAY, GRAY, WATER, WATER
